# Generated by Django 4.0 on 2022-01-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_remove_friend_users_friend_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
