# Generated by Django 4.0 on 2022-01-10 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='feed.note'),
        ),
    ]
