# Generated by Django 4.0 on 2022-01-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_like_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, help_text='Введите фамилию', max_length=64),
        ),
        migrations.AlterField(
            model_name='like',
            name='vote',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
