# Generated by Django 4.0 on 2022-01-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_friendrequest_hidden_alter_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.BooleanField(default=False),
        ),
    ]
